### ISSUE TITLE
#18 이메일 인증 구현

### ISSUE THREAD

**Issue by seongchankim1** [seongchankim1/newsfeed#18]
1. 인증키 만들기 ? -> Token 그냥ㄴ 숫자? - 제가
2. 인증키 이메일 발송 -> 등록된 이메일 주소로 발송
- (authKey) - 근수
3. 비교해서 승인하고 인증 상태 변경

**Comment by haze0827** [comment]
비교해서 승인하고 인증 상태 변경(구현중)
